/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SociosRouteImport } from './routes/socios'
import { Route as PublicacoesRouteImport } from './routes/publicacoes'
import { Route as EscritorioRouteImport } from './routes/escritorio'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as IndexRouteImport } from './routes/index'

const SociosRoute = SociosRouteImport.update({
  id: '/socios',
  path: '/socios',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicacoesRoute = PublicacoesRouteImport.update({
  id: '/publicacoes',
  path: '/publicacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EscritorioRoute = EscritorioRouteImport.update({
  id: '/escritorio',
  path: '/escritorio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/areas': typeof AreasRoute
  '/contato': typeof ContatoRoute
  '/escritorio': typeof EscritorioRoute
  '/publicacoes': typeof PublicacoesRoute
  '/socios': typeof SociosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/areas': typeof AreasRoute
  '/contato': typeof ContatoRoute
  '/escritorio': typeof EscritorioRoute
  '/publicacoes': typeof PublicacoesRoute
  '/socios': typeof SociosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/areas': typeof AreasRoute
  '/contato': typeof ContatoRoute
  '/escritorio': typeof EscritorioRoute
  '/publicacoes': typeof PublicacoesRoute
  '/socios': typeof SociosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/areas'
    | '/contato'
    | '/escritorio'
    | '/publicacoes'
    | '/socios'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/areas' | '/contato' | '/escritorio' | '/publicacoes' | '/socios'
  id:
    | '__root__'
    | '/'
    | '/areas'
    | '/contato'
    | '/escritorio'
    | '/publicacoes'
    | '/socios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreasRoute: typeof AreasRoute
  ContatoRoute: typeof ContatoRoute
  EscritorioRoute: typeof EscritorioRoute
  PublicacoesRoute: typeof PublicacoesRoute
  SociosRoute: typeof SociosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/socios': {
      id: '/socios'
      path: '/socios'
      fullPath: '/socios'
      preLoaderRoute: typeof SociosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicacoes': {
      id: '/publicacoes'
      path: '/publicacoes'
      fullPath: '/publicacoes'
      preLoaderRoute: typeof PublicacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escritorio': {
      id: '/escritorio'
      path: '/escritorio'
      fullPath: '/escritorio'
      preLoaderRoute: typeof EscritorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreasRoute: AreasRoute,
  ContatoRoute: ContatoRoute,
  EscritorioRoute: EscritorioRoute,
  PublicacoesRoute: PublicacoesRoute,
  SociosRoute: SociosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
